---

- assert:
    that:
      - eclipse_url_safe
    msg: 'Could not determine Eclipse build name from eclipse url, please check eclipse_url var'

- file: path=/var/tmp/ansible-eclipse state=directory
  changed_when: false
  delegate_to: localhost
  become: no

- get_url:
    url: '{{ eclipse_url }}'
    dest: /var/tmp/ansible-eclipse/{{ eclipse_pkg_file_name }}
  changed_when: false
  delegate_to: localhost
  become: no

- copy:
    src: /var/tmp/ansible-eclipse/{{ eclipse_pkg_file_name }}
    dest: /tmp/
  changed_when: false

- package: name={{item}} state=present
  with_items:
    - tar
    - sudo
    - java-headless

- file: path={{ eclipse_pkg_dir }} state=directory

- command: tar xz -f /tmp/{{ eclipse_pkg_file_name }} 
    -C {{ eclipse_pkg_dir }} --strip-components=1 --no-same-owner --no-same-permissions
  args:
    creates: '{{ eclipse_pkg_dir }}/eclipse'

- alternatives: name=eclipse link={{ eclipse_dir }} path={{ eclipse_pkg_dir }}

- replace:
    dest: /etc/sudoers
    regexp: (secure_path(?!.*{{ eclipse_dir }}.*).*)
    replace: '\1:{{ eclipse_dir }}'
    backup: yes

- template: src=ansible-eclipse.sh.j2 dest=/etc/profile.d/ansible-eclipse.sh

- template: src=ansible-eclipse.desktop.j2 dest={{ applications_dir }}/ansible-eclipse.desktop
