---
- yum: name="@java-development" state=present

- yum: name={{item}} state=present
  with_items:
    - tar
    - sudo

- get_url:
    url: "{{ eclipse_url }}"
    dest: /var/tmp/eclipse.tar.gz

- file: path={{ eclipse_dir }} state=directory

- command: tar xz -f /var/tmp/eclipse.tar.gz -C {{ eclipse_dir }} --strip-components=1 --no-same-owner --no-same-permissions
  args:
    creates: "{{ eclipse_dir }}/eclipse"
  
- replace:
    dest: /etc/sudoers
    regexp: (secure_path(?!.*{{ eclipse_dir }}.*).*)
    replace: '\1:{{ eclipse_dir }}'
    backup: yes

- template: src=eclipse.sh.j2 dest=/etc/profile.d/eclipse.sh

- template: src=eclipse.desktop.j2 dest={{ applications_dir }}/eclipse.desktop
